### ISSUE TITLE
Unable to change or disable open GUI hotkey

### ISSUE THREAD

**Issue by dlfnn** [DarkKronicle/DarkKore#1]
it just stay as "j", which i want it to be the hotkey of the world map mod. I tried editing in-game, and editing \config\darkkore.toml, but everytime it just reset to "j".

**Comment by DarkKronicle** [comment]
Hmm this is a really weird bug. What version of the mod are you using?

**Comment by dlfnn** [comment]
> Hmm this is a really weird bug. What version of the mod are you using?

tried 0.3.0 and 0.3.1 (1.19.2)

**Comment by DarkKronicle** [comment]
are there any errors in the log when it happens?
